project_id = "wmxtzkrkscjwixafumym"

[functions.send-notification]
verify_jwt = true

[functions.appointment-reminders]
verify_jwt = false

[functions.lab-critical-values]
verify_jwt = false

[functions.check-low-stock]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.verify-totp]
verify_jwt = false
